name: adk_dart
description: Core Dart port of Agent Development Kit (ADK) runtime primitives.
version: 0.1.0
repository: https://github.com/adk-labs/adk_dart
homepage: https://github.com/adk-labs/adk_dart
issue_tracker: https://github.com/adk-labs/adk_dart/issues

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

executables:
  adk: adk

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
